### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by carleyestes** [dryuen/ist5313-f18-fp1#2]
**Question:**  How will this course be structured?  Will they need to complete each “tab” at the top before they can move to the quiz and earn a certificate?  
**Recommendation:** make a completion bar that only allows you to take the quiz if you’ve completed the entire module, maybe shows a checklist with each section checked off so that the user knows which one was missed.

**Question:** will there be a main menu for each module or will the user need to have 3 separate links? 
**Recommendation:** create a master “tree” or side menu that shows the entire course content (minus each individual lesson)

I really love the look of your website, it appears to be modeled after a card catalog of recipes.  

I know this was supposed to just be “wire frames” of the storyboard, but you even made working quizzes…wondering if they will have immediate validation if they were answered correctly or what that will look like.

overall, A+ !

**Comment by rcryer** [comment]
Dr.Yuen suggested that all pages be open in the storyboard. once content is loaded certain pages will be hidden until the user has accessed the previous page. 
I believe the Moodle will have outside links to the modules so internal links will be redundant.
