### ISSUE TITLE
Sequence

### ISSUE THREAD

**Issue by cullenbay** [dryuen/ist5313-f18-fp1#3]
•	Recommend having on overview of the content with goals/outcomes for the learner (ie. At the end of this lesson you will be able to…..)
•	Ensure sequence is structured in a manner that users will go from one lesson to another in a logical manner. Seems that users can go to any lesson, maybe incorporate gating to open lesson in order or you can number them so users know they have to go in sequence. 
•	Ensure the user cannot access the assessment section unless s/he has visited all required lessons.

**Comment by rcryer** [comment]
This is a content issue. Storyboards are only for a general outline of the page structure. The overview will be set up in the Alpha. The coding of each page is set up so that the content only need be added.
