### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by cullenbay** [dryuen/ist5313-f18-fp1#4]
•	Navigation is laid out well so that the user can see what all requirements are needed to finish the module. Recommend building a table of contents or build a module overview as your first lesson. 
•	Overall look and feel of the course is aesthetically appealing. (great use of color scheme and pics)
•	Overall layout of space and content is well utilized (feel spacious and not crammed)
•	Ensure all users understand the flow of the course meaning how to proceed from one lesson to another and once a module is complete what is next. Use a note (Congrats, now proceed to Module ?? after they receive certificate)

**Comment by rcryer** [comment]
This is all content based. not design. the content determines the meaning and user requirements of the module. A proceed to the next module is in the work for the Alpha.
