### ISSUE TITLE
Assessments/Quiz

### ISSUE THREAD

**Issue by cullenbay** [dryuen/ist5313-f18-fp1#5]
•	Ensure the user cannot access the certificate of completion unless s/he has passed the assessment. 
•	Make sure that the quiz has a score at the end and when a score of 70% is achieved the certificate if available.

**Comment by rcryer** [comment]
This is part of the beta process. Assessments are rated once the content is added and the alpha has been assessed. the current quiz is a placeholder in the code for the storyboard.
